import AppKit
import Observation

/// One text copy seen on the general pasteboard.
struct ClipEntry: Identifiable, Equatable {
    let id = UUID()
    let text: String
    var date: Date
    /// Where the copy came from: a tab title for copies made in this app, else the app's name.
    var source: String?
    /// Set for copies made in another app, to show its icon.
    var appURL: URL?
}

/// Clipboard history for the sidebar. macOS posts no notification when the
/// pasteboard changes, so this polls `changeCount`, which is what every clipboard
/// manager does. Kept in memory only: copied text never touches the disk.
@MainActor
@Observable
final class ClipboardHistory {
    private(set) var entries: [ClipEntry] = []
    /// Bumped for every new copy, so views can flash.
    private(set) var flashCount = 0
    private(set) var lastAddedID: UUID?

    static let limit = 50

    /// Names a copy made while this app is frontmost (the key window's active tab).
    @ObservationIgnored var localSource: () -> String? = { nil }
    @ObservationIgnored private var changeCount = NSPasteboard.general.changeCount
    @ObservationIgnored private var timer: Timer?

    /// nspasteboard.org markers: password managers and the like ask not to be recorded.
    private static let skippedTypes: Set<NSPasteboard.PasteboardType> = [
        .init("org.nspasteboard.ConcealedType"),
        .init("org.nspasteboard.TransientType"),
        .init("org.nspasteboard.AutoGeneratedType"),
        .init("com.agilebits.onepassword"),
    ]

    func start() {
        guard timer == nil else { return }
        timer = Timer.scheduledTimer(withTimeInterval: 0.4, repeats: true) { [weak self] _ in
            MainActor.assumeIsolated { self?.poll() }
        }
    }

    private func poll() {
        let pb = NSPasteboard.general
        guard pb.changeCount != changeCount else { return }
        changeCount = pb.changeCount
        let types = Set(pb.types ?? [])
        guard types.isDisjoint(with: Self.skippedTypes),
              let text = pb.string(forType: .string),
              !text.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty else { return }
        let front = NSWorkspace.shared.frontmostApplication
        let isLocal = front?.processIdentifier == ProcessInfo.processInfo.processIdentifier
        add(text, source: isLocal ? localSource() : front?.localizedName,
            appURL: isLocal ? nil : front?.bundleURL)
    }

    /// Records a copy. Copying something already in the list moves it to the top.
    func add(_ text: String, source: String?, appURL: URL? = nil) {
        entries.removeAll { $0.text == text }
        let entry = ClipEntry(text: text, date: Date(), source: source, appURL: appURL)
        entries.insert(entry, at: 0)
        if entries.count > Self.limit { entries.removeLast(entries.count - Self.limit) }
        lastAddedID = entry.id
        flashCount += 1
    }

    /// Puts an entry back on the clipboard without recording it as a new copy.
    func restore(_ entry: ClipEntry) {
        let pb = NSPasteboard.general
        pb.clearContents()
        pb.setString(entry.text, forType: .string)
        changeCount = pb.changeCount
    }

    func remove(_ entry: ClipEntry) { entries.removeAll { $0.id == entry.id } }

    func clear() { entries.removeAll() }
}
