import AppKit
import Observation

/// What a copy held. Finder copies are `.files`; screenshots and "Copy Image" are `.image`.
enum ClipContent {
    case text(String)
    case image(Data, type: NSPasteboard.PasteboardType, pixels: CGSize)
    case files([URL])

    /// Identity for de-duplication: copying the same thing again moves it to the top.
    var key: String {
        switch self {
        case .text(let s): "t:" + s
        case .image(let d, _, _): "i:\(d.count):\(d.hashValue)"
        case .files(let urls): "f:" + urls.map(\.path).joined(separator: "\n")
        }
    }
}

/// One copy seen on the general pasteboard.
struct ClipEntry: Identifiable {
    let id = UUID()
    let content: ClipContent
    var date: Date
    /// Where the copy came from: a tab title for copies made in this app, else the app's name.
    var source: String?
    /// Set for copies made in another app, to show its icon.
    var appURL: URL?
    /// Decoded once for `.image`, so rows don't re-decode on every render.
    var thumbnail: NSImage?
}

/// Clipboard history for the sidebar. macOS posts no notification when the
/// pasteboard changes, so this polls `changeCount`, which is what every clipboard
/// manager does. Kept in memory only; an image is written to a temporary file
/// only when you paste it into a tab.
@MainActor
@Observable
final class ClipboardHistory {
    private(set) var entries: [ClipEntry] = []
    /// Bumped for every new copy, so views can flash.
    private(set) var flashCount = 0
    private(set) var lastAddedID: UUID?

    static let limit = 50
    /// Images can be large (a Retina screenshot is several MB); oldest images go first past this.
    static let imageBytesLimit = 200 * 1024 * 1024

    /// Names a copy made while this app is frontmost (the key window's active tab).
    @ObservationIgnored var localSource: () -> String? = { nil }
    @ObservationIgnored private var changeCount = NSPasteboard.general.changeCount
    @ObservationIgnored private var timer: Timer?

    /// nspasteboard.org markers: password managers and the like ask not to be recorded.
    private static let skippedTypes: Set<NSPasteboard.PasteboardType> = [
        .init("org.nspasteboard.ConcealedType"),
        .init("org.nspasteboard.TransientType"),
        .init("org.nspasteboard.AutoGeneratedType"),
        .init("com.agilebits.onepassword"),
    ]
    private static let imageTypes: [NSPasteboard.PasteboardType] = [.png, .tiff, .init("public.jpeg"), .init("public.heic")]

    /// Where images go when pasted into a tab as a path. Cleared at launch.
    static let spoolDirectory = FileManager.default.temporaryDirectory.appendingPathComponent("SmartTerminal Clips")

    func start() {
        guard timer == nil else { return }
        try? FileManager.default.removeItem(at: Self.spoolDirectory)
        timer = Timer.scheduledTimer(withTimeInterval: 0.4, repeats: true) { [weak self] _ in
            MainActor.assumeIsolated { self?.poll() }
        }
    }

    private func poll() {
        let pb = NSPasteboard.general
        guard pb.changeCount != changeCount else { return }
        changeCount = pb.changeCount
        guard Set(pb.types ?? []).isDisjoint(with: Self.skippedTypes),
              let content = Self.read(pb) else { return }
        let front = NSWorkspace.shared.frontmostApplication
        let isLocal = front?.processIdentifier == ProcessInfo.processInfo.processIdentifier
        add(content, source: isLocal ? localSource() : front?.localizedName,
            appURL: isLocal ? nil : front?.bundleURL)
    }

    /// Files first (Finder also puts the file name as text and its icon as an image),
    /// then an image if that's the richest thing on offer, else text. Apps that copy
    /// text often add a picture of it (Numbers, Excel), so text wins unless the image
    /// comes first in the pasteboard's own order.
    private static func read(_ pb: NSPasteboard) -> ClipContent? {
        if let urls = pb.readObjects(forClasses: [NSURL.self], options: [.urlReadingFileURLsOnly: true]) as? [URL],
           !urls.isEmpty {
            return .files(urls)
        }
        let types = pb.types ?? []
        let text = pb.string(forType: .string).flatMap { $0.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty ? nil : $0 }
        let firstImage = types.firstIndex { imageTypes.contains($0) }
        let firstText = types.firstIndex { $0 == .string }
        if let i = firstImage, text == nil || i < (firstText ?? .max) {
            let type = types[i]
            if let data = pb.data(forType: type), let rep = NSBitmapImageRep(data: data) {
                return .image(data, type: type, pixels: CGSize(width: rep.pixelsWide, height: rep.pixelsHigh))
            }
        }
        return text.map(ClipContent.text)
    }

    /// Records a copy. Copying something already in the list moves it to the top.
    func add(_ content: ClipContent, source: String?, appURL: URL? = nil) {
        entries.removeAll { $0.content.key == content.key }
        var entry = ClipEntry(content: content, date: Date(), source: source, appURL: appURL)
        if case .image(let data, _, _) = content { entry.thumbnail = NSImage(data: data) }
        entries.insert(entry, at: 0)
        trim()
        lastAddedID = entry.id
        flashCount += 1
    }

    private func trim() {
        if entries.count > Self.limit { entries.removeLast(entries.count - Self.limit) }
        var bytes = 0
        entries = entries.filter { e in
            guard case .image(let d, _, _) = e.content else { return true }
            bytes += d.count
            return bytes <= Self.imageBytesLimit || e.id == entries.first?.id
        }
    }

    /// Puts an entry back on the clipboard without recording it as a new copy.
    func restore(_ entry: ClipEntry) {
        let pb = NSPasteboard.general
        pb.clearContents()
        switch entry.content {
        case .text(let s): pb.setString(s, forType: .string)
        case .image(let d, let type, _): pb.setData(d, forType: type)
        case .files(let urls): pb.writeObjects(urls as [NSURL])
        }
        changeCount = pb.changeCount
    }

    /// What pasting an entry into a shell types: the text, or shell-quoted paths plus a space.
    /// An image is saved as a PNG first, so its path works for the shell and for
    /// Claude Code, which attaches an image when its path is pasted.
    func pasteText(for entry: ClipEntry) -> String? {
        switch entry.content {
        case .text(let s):
            return s
        case .files(let urls):
            // Trailing space, like Terminal.app after a file drop, so paths don't run together.
            return urls.map { Self.shellQuoted($0.path) }.joined(separator: " ") + " "
        case .image(let data, _, _):
            guard let png = NSBitmapImageRep(data: data)?.representation(using: .png, properties: [:]) else { return nil }
            let fm = FileManager.default
            try? fm.createDirectory(at: Self.spoolDirectory, withIntermediateDirectories: true)
            let stamp = entry.date.formatted(.iso8601.year().month().day().time(includingFractionalSeconds: false))
                .replacingOccurrences(of: ":", with: ".")
            let url = Self.spoolDirectory.appendingPathComponent("Clip \(stamp).png")
            guard (try? png.write(to: url)) != nil else { return nil }
            return Self.shellQuoted(url.path) + " "
        }
    }

    static func shellQuoted(_ s: String) -> String {
        let safe = CharacterSet(charactersIn: "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789/._-+,:@%")
        if !s.isEmpty, s.unicodeScalars.allSatisfy(safe.contains) { return s }
        return "'" + s.replacingOccurrences(of: "'", with: "'\\''") + "'"
    }

    func remove(_ entry: ClipEntry) { entries.removeAll { $0.id == entry.id } }

    func clear() { entries.removeAll() }
}
